---
config:
  imagesPath: img/characters/
  playerCharacter: player
  gameCharacter: game
characters:
  game:
    name: ''
    color: white
  player:
    style:
      color: orange
    sprites:
      idle: none
    name: You
