allowChoosingFont: false
fontSets:
  default:
    header:
      name: Baskervville SC
      fontFamily: '"Baskervville SC", serif'
      files: ['fonts/Baskervville_SC/BaskervvilleSC-Regular.ttf']
    body:
      name: Baskervville SC
      fontFamily: '"Baskervville SC", serif'
      files:
        - file: 'fonts/Baskervville_SC/BaskervvilleSC-Regular.ttf'
          options: {}
        - file: 'fonts/Baskervville_SC/BaskervvilleSC-Regular.ttf'
          options:
            style: italic
  custom:
    header:
      name: Baskervville SC
      fontFamily: '"Baskervville SC", serif'
      files: ['fonts/Baskervville_SC/BaskervvilleSC-Regular.ttf']
    body:
      name: Baskervville SC
      fontFamily: '"Baskervville SC", serif'
      files: ['fonts/Baskervville_SC/BaskervvilleSC-Regular.ttf']
  opendyslexic:
    header:
      name: 'OpenDyslexic'
      fontFamily: '"OpenDyslexic", sans-serif'
      files:
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Regular.woff2'
          options:
            weight: 400
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Bold.woff2'
          options:
            weight: 700
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Italic.woff2'
          options:
            style: italic
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Bold-Italic.woff2'
          options:
            weight: 700
            style: italic
    body:
      name: 'OpenDyslexic'
      fontFamily: '"OpenDyslexic", sans-serif'
      files:
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Regular.woff2'
          options:
            weight: 400
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Bold.woff2'
          options:
            weight: 700
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Italic.woff2'
          options:
            style: italic
        - file: 'fonts/OpenDyslexic/OpenDyslexic-Bold-Italic.woff2'
          options:
            weight: 700
            style: italic
